### ISSUE TITLE
zkSync Adjustements 

### ISSUE THREAD

**Issue by Redoudou** [Jovells/zksync-web3js-paymaster-demo#1]
- [ ]  Page title is "React App", probably can easily be renamed to something more reflective.
- [ ]  Looks like it automatically tries to connect the wallet. My MetaMask was connected to a different network and it still generated a connection request.
- [ ] If there is an active connection request and you click "Connect wallet", it shows an error.
- [ ] When I clicked on "Mint mUSDT", it initially showed an error pop-up "Please connect your wallet". When I clicked for 2nd time, it worked.
- [ ] Looks like once you make a purchase, you can only go to the past purchases, but not back to the shop. Same for past purchases -- you can only click on the "zkSync Demo" in the top left corner to get back to the home page.
- [ ] After making a purchase, looks like mUSDT balance is not updated.
- [ ] "Explore Products" and "Buy Product" lead to the same page.
- [ ] When you buy products, you can see "Quantity", but it's empty.
- [ ] "View Purchase History" on the main page doesn't seem to work. Looks like the URL there is `/purchase-history`, while the correct one is `/past-purchases`.
- [ ] When paying with paymaster, maybe it makes sense to explain that the first transaction is `approve` and the second transaction is the actual purchase.
- [ ] adding a disconnect wallet button on top right corner 
- [ ] https://web3js-zksync-plugin.vercel.app/products?id=1 link does not bring to product page bellow. The product page shows but I guess the expected behavior is scrolling down.
- [ ] Next to 
![telegram-cloud-photo-size-1-5141097831115894736-y](https://github.com/user-attachments/assets/a221d6ba-11a3-4d5d-a732-187b221f994c) should be displayed the token contract address so it is easy to add to MM
- [ ] Next to "By Jovell" - I would not be shocked if you shill your profile more ( twitter / LinkedIn /  Avatar)

**Comment by Jovells** [comment]
All these have been resolved in the latest release. Thanks for the feedback
